{
 "title": "URLShortener",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "Instance",
    "label": "Instance",
    "query": {
     "query": "label_values(up{job=\"urlshortener\"}, instance)"
    }
   },
   { "name": "Quantile", "label": "Quantile", "query": "0.5, 0.9, 0.95, 0.99" }
  ]
 },
 "panels": [
  { "title": "HTTP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(urlshortener_http_request_total{instance=~\"$Instance\"}[1m])) by (code, method, url)",
     "legendFormat": "{{method}} {{url}} => {{code}}"
    }
   ]
  },
  {
   "title": "Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($Quantile, rate(urlshortener_http_request_duration_seconds_bucket{code=\"200\", instance=~\"$Instance\"}[1m]))",
     "legendFormat": "{{host}} => {{method}} {{url}}"
    }
   ]
  },
  {
   "title": "Average Request Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "urlshortener_http_request_duration_seconds_sum{code=\"200\",instance=~\"$Instance\",job=\"urlshortener\"} /\nurlshortener_http_request_duration_seconds_count{code=\"200\",instance=~\"$Instance\",job=\"urlshortener\"}\t",
     "legendFormat": "{{method}}"
    }
   ]
  },
  { "title": "Database", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Repository Error Rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(urlshortener_repo_error_total{instance=\"192.168.178.12:9001\",job=\"urlshortener\",repo_name=\"sql_URL\"}[1m])",
     "legendFormat": "{{repo_method}}"
    }
   ]
  },
  {
   "title": "Repository Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile($Quantile, rate(urlshortener_repo_duration_total_bucket{repo_name=\"sql_URL\", instance=~\"$Instance\"}[1m]))",
     "legendFormat": "{{repo_method}}"
    }
   ]
  },
  {
   "title": "Average repository Duration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "urlshortener_repo_duration_total_sum{instance=~\"$Instance\", repo_name=\"sql_URL\"}/\nurlshortener_repo_duration_total_count{instance=~\"$Instance\",repo_name=\"sql_URL\"}\t",
     "legendFormat": "{{repo_method}}"
    }
   ]
  },
  { "title": "Golang", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 } },
  {
   "title": "Go routins",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "go_goroutines{instance=\"192.168.178.12:9001\",job=\"urlshortener\"}"
    }
   ]
  }
 ]
}