version: "3.6"
services:

  postgres:
    image: postgres:13.2
    hostname: postgres
    container_name: postgres
    environment:
      POSTGRES_DB: urldb
      POSTGRES_PASSWORD: secret
      POSTGRES_USER: urldb
    ports:
      - 5432:5432

  redis:
    image: redis:6.2.4-alpine
    hostname: redis
    container_name: redis
    ports:
      - 6379:6379

#  urlshortener:
#    image: urlshortener:latest
#    hostname: urlshortener
#    container_name: urlshortener
#    environment:
#      URLSHORTENER_DATABASE_MASTER_CONN_STRING: postgresql://urldb:secret@postgres:5432/urldb?sslmode=disable&connect_timeout=30
#      URLSHORTENER_DATABASE_SLAVE_CONN_STRING: postgresql://urldb:secret@postgres:5432/urldb?sslmode=disable&connect_timeout=30
#    ports:
#      - 8080:8080

#  prometheus:
#    image: prom/prometheus:v2.27.1
#    hostname: prometheus
#    container_name: prometheus
#    command:
#      - '--config.file=/etc/prometheus/prometheus.yml'
#      - '--storage.tsdb.path=/prometheus'
#      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
#      - '--web.console.templates=/usr/share/prometheus/consoles'
#    volumes:
#      - ./prometheus.yml:/etc/prometheus/prometheus.yml
#    ports:
#      - 9090:9090
#
#  grafana:
#    image: grafana/grafana:7.5.7
#    hostname: grafana
#    container_name: grafana
#    ports:
#      - 3000:3000
